### ISSUE TITLE
Does it work on android?

### ISSUE THREAD

**Issue by andrey-grach** [enzomanuelmangano/animate-with-reanimated#3]
Thanks for good tutorial. On iOS works fine but on Android in my case doesn't work.... So I'm just wondering if you tested this on Android?

**Comment by andrey-grach** [comment]
Okay, after a little investigation I found out that on Android you also should wrap the Root Component with the GestureHandlerRootView component (from react-native-gesture-handler):

```
      <GestureHandlerRootView style={{flex: 1}}>
        <PinchGestureHandler onGestureEvent={pinchHandler}>
          <Animated.View style={{flex: 1}}>
            <AnimatedImage style={[{width: 300, height: 300, alignSelf: 'center'}, rStyle]} uri={'imageuri'} />
            <Animated.View style={[focalPointStyle]}/>
          </Animated.View>
        </PinchGestureHandler>
      </GestureHandlerRootView>
```

**Comment by valeriiashpiner** [comment]
Android flickers for me for some reason. Do you have the same issue?

**Comment by amwebexpert** [comment]
Yes I'm on Android device
 I'll give it a try from my desktop...
